USE SCHEMA DEMO;

CREATE OR REPLACE PROCEDURE SAMPLE_PROC_SF()
RETURNS TABLE (FIRST_NAME VARCHAR(16777216), LAST_NAME VARCHAR(16777216))
LANGUAGE SQL
EXECUTE AS OWNER
AS
DECLARE
  res RESULTSET DEFAULT (SELECT FIRST_NAME,LAST_NAME FROM  HELLO_WORLD );
BEGIN
  RETURN TABLE(res);
END;
 